if_snp: True
if_ht: False
if_structure: True
if_RNA_snp_split: False
if_charm: True

ref_genome: GRCm38  
yperx_threshold: 0.015 # GM12878 is all female,set a bigger value
softwares:
  CHARMtools: /zliu_ssd/CHARM/upload/CHARMtools
refs:
  GRCm38:
    bwa_mem2_index: /share/Data/public/ref_genome/mouse_ref/M23/bwamem2/genome.fa
    star_index: /share/Data/public/ref_genome/mouse_ref/M23/RNA_snp_split/CAST_B6_star_index
    annotations: /share/Data/public/ref_genome/mouse_ref/M23/raw_data/annotation.gtf
    snp: /share/home/zliu/share/Data/public/ref_genome/GRCm38/snp/Tan.CAST_B6.snp.GRCm38.withchr.txt
    par: /share/home/zliu/share/Data/public/ref_genome/GRCm38/raw_data/par.bed
    RNAsnp: /share/home/zliu/share/Data/public/ref_genome/mouse_ref/M23/RNA_snp_split/all_SNPs_CAST_EiJ_GRCm38.txt.gz

  GRCh37d5:
    bwa_mem2_index: /share/Data/public/ref_genome/GRCh37d5/bwa_mem2_index/genome.fa
    star_index: /share/Data/public/ref_genome/human_ref/GRCh37d5/RNA_snp_split/NA12878_star_index
    annotations: /share/Data/public/ref_genome/GRCh37/raw_data/gencode.v19.annotation.gtf
    snp: /share/home/zliu/share/Data/public/ref_genome/GRCh37/snp_file/GM12878/NA12878.withchr.txt
    par: /share/home/zliu/share/Data/public/ref_genome/GRCh37/raw_data/par.withchr.bed
    RNAsnp: /share/Data/public/ref_genome/human_ref/GRCh37d5/RNA_snp_split/NA12878.withchr.SNPsplit.txt.gz

  rab:
    bwa_mem2_index: /share/Data/public/ref_genome/rabbit_ref/bwamem2/GCF_009806435.1_UM_NZW_1.0_genomic.fna
    star_index: /share/Data/public/ref_genome/rabbit_ref/star_index
    annotations: /share/Data/public/ref_genome/rabbit_ref/rawdata/genomic.gtf
    snp: /share/Data/public/ref_genome/GRCh37/snp_file/GM12878/NA12878.withchr.txt
    par: /share/Data/public/ref_genome/GRCh37/snp_file/GM12878/NA12878.withchr.txt
    RNAsnp: /share/Data/public/ref_genome/GRCh37/snp_file/GM12878/NA12878.withchr.txt
split:
  ct: XGGTTGAGGTAGTGGTATAGCTTCGTGTATAAGAGACAG;o=32
  atac: XGGTTGAGGTAGTAAGTCCTGGATGTGTATAAGAGACAG;o=32

resources:
  cutadapt_cpu_threads: 5
  bwa_cpu_threads: 7
  hires_clean_cpu_threads: 5 
  star_cpu_threads: 20
  align2pairs_cpu_threads: 6
  count_cpu_threads: 6
  generateStat_cpu_threads: 40
